docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v3
  versions:
    - v3
nav:
  - Home: index.md
  - v3:
      - Overview: v3/overview.md
      - Configuration: v3/configuration.md
      - Installation: v3/installation.md
      - Components: v3/components.md
      - "Container Providers": v3/container-providers.md
      - "Navigation Renderer": v3/navigation-renderer.md
      - "Required Page Options": v3/required-page-options.md
      - Usage: v3/usage.md
site_name: dot-navigation
site_description: "DotKernel's component that allows you to easily define and parse menus inside templates, using a configuration based approach."
repo_url: "https://github.com/dotkernel/dot-navigation"
plugins:
  - search
